// src/scripts/generate-sw.ts
import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';
import { siteDefaults } from '../config/siteDefaults';

const swPath = path.resolve('./public/sw.js');
const offlineHtmlPath = path.resolve('./public/offline.html');

// ---- paths for modified-time tracking ----
const assetsManifestPath = path.resolve('./src/data/assets-manifest.json');
const siteDefaultsPath = path.resolve('./src/config/siteDefaults.ts');

// ---- read/write helpers ----
async function readJson<T = any>(p: string): Promise<T> {
  const raw = await fs.readFile(p, 'utf8');
  return JSON.parse(raw) as T;
}

async function writeJson(p: string, data: any) {
  await fs.writeFile(p, JSON.stringify(data, null, 2) + '\n', 'utf8');
}

async function getMTimeMs(p: string): Promise<number> {
  const s = await fs.stat(p);
  return Math.floor(s.mtimeMs);
}

// ---- ensure configModified.siteDefaults is up-to-date ----
const manifest = await readJson<any>(assetsManifestPath);
manifest.configModified ||= {};

const lastRecorded = Number(manifest.configModified.siteDefaults || 0);
const currentMTime = await getMTimeMs(siteDefaultsPath);

if (!lastRecorded || currentMTime > lastRecorded) {
  manifest.configModified.siteDefaults = currentMTime;
  await writeJson(assetsManifestPath, manifest);
  console.log(
    `📝 Updated assets-manifest.json: configModified.siteDefaults=${currentMTime}`
  );
}

// ---- build a stable cache version from configModified ----
const cfg = manifest.configModified || {};
const cacheSeed = [
  cfg.siteDefaults,
  cfg.siteLogo,
  cfg.siteColors,
  cfg.siteImages,
].filter(Boolean).join('|');

const cacheVersion =
  (cacheSeed &&
    crypto.createHash('md5').update(String(cacheSeed)).digest('hex').slice(0, 8)) ||
  // fallback (should rarely be used)
  Math.random().toString(36).slice(2, 10);

const cacheNameSlug = (siteDefaults.siteName || 'site')
  .replace(/\s+/g, '-')
  .toLowerCase();
const CACHE_NAME = `${cacheNameSlug}-cache-${cacheVersion}`;

// ---- CDN prefix ----
const cdn = (siteDefaults.cdnPath || '').replace(/\/+$/, '');

function addCDNPrefix(p: string): string {
  if (!p) return '';
  if (cdn && !/^https?:\/\//.test(p)) return `${cdn}${p}`;
  return p;
}

// ---- asset helpers ----
// NOTE: we re-read the manifest from disk above so it’s current.
function extractPaths(
  section: Record<string, { file?: string }> | undefined
): string[] {
  if (!section) return [];
  return Object.values(section).map((e) => e.file).filter(Boolean) as string[];
}

async function fileExists(publicPath: string): Promise<boolean> {
  const fullPath = path.resolve('./public', publicPath.replace(/^\//, ''));
  try {
    await fs.access(fullPath);
    return true;
  } catch {
    return false;
  }
}

// ---- ensure offline.html exists (uses siteDefaults) ----
async function ensureOfflineHtml() {
  try {
    await fs.access(offlineHtmlPath);
  } catch {
    const title = siteDefaults.siteName || 'Offline';
    const description = siteDefaults.description || 'You are currently offline.';
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title} - Offline</title>
  <style>
    html, body {
      margin: 0; padding: 0;
      font-family: system-ui, sans-serif;
      text-align: center;
      display: flex;
      flex-direction: column;
      justify-content: center;
      min-height: 100vh;
      background-color: #f8f8f8;
    }
    h1 { color: #444; font-size: 1.8rem; }
    p { color: #777; font-size: 1rem; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p>${description}</p>
  <p>Please check your internet connection.</p>
</body>
</html>`.trim();
    await fs.writeFile(offlineHtmlPath, html, 'utf8');
    console.log('📝 Created fallback offline.html');
  }
}

// === Generate and write SW ===
await ensureOfflineHtml();

// Optional: pre-cache lists from manifest (kept minimal here)
// const jsPaths = extractPaths(manifest.js);
// const cssPaths = [
//   ...extractPaths(manifest.css?.main),
//   ...extractPaths(manifest.css?.nonCritical),
//   ...extractPaths(manifest.css?.preload),
// ];

const additionalPaths = siteDefaults.serviceWorkerPaths ?? [];

const allPaths = [
  '/',                // homepage
  '/offline.html',    // offline fallback
  // ...cssPaths,
  // ...jsPaths,
  ...additionalPaths,
];

// Keep only existing local files
const filteredPaths = await Promise.all(
  allPaths.map(async (p) => {
    if (/^https?:\/\//.test(p)) return p;
    const exists = await fileExists(p);
    return exists ? p : null;
  })
);

const precachePaths = [...new Set(filteredPaths.filter(Boolean) as string[])]
  .map(addCDNPrefix);

const swContent = `
// ✅ Auto-generated by generate-sw.ts
const CACHE_NAME = '${CACHE_NAME}';
const PRECACHE_URLS = ${JSON.stringify(precachePaths, null, 2)};

self.addEventListener('install', (event) => {
  console.log('[SW] Installing...');
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      for (const url of PRECACHE_URLS) {
        try {
          const res = await fetch(url, { credentials: 'same-origin' });
          if (res.ok) {
            await cache.put(url, res.clone());
          } else {
            console.warn('[SW] Skipped caching (not OK):', url);
          }
        } catch (e) {
          console.warn('[SW] Failed to fetch during install:', url, e);
        }
      }
    })
  );
});

self.addEventListener('activate', (event) => {
  console.log('[SW] Activating...');
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.map((key) => {
          if (key !== CACHE_NAME) {
            console.log('[SW] Removing old cache:', key);
            return caches.delete(key);
          }
        })
      )
    )
  );
  return self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;

  if (req.method !== 'GET') return;

  const url = new URL(req.url);

  if (url.origin !== self.location.origin) return;

  if (req.destination === 'font') {
    event.respondWith(staleWhileRevalidate(req));
    return;
  }

  if (req.destination === 'style' || req.destination === 'script') {
    event.respondWith(staticCache(req));
    return;
  }

  if (req.mode === 'navigate') {
    event.respondWith(fetch(req).catch(() => caches.match('/offline.html')));
    return;
  }

  event.respondWith(fetch(req).catch(() => caches.match(req)));
});

async function staleWhileRevalidate(req) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(req);
  const networkFetch = fetch(req).then(res => {
    if (res.ok) cache.put(req, res.clone());
    return res;
  }).catch(() => null);
  return cached || networkFetch;
}

async function staticCache(req) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(req);
  if (cached) return cached;
  try {
    const res = await fetch(req);
    if (res.ok) cache.put(req, res.clone());
    return res;
  } catch {
    return cached;
  }
}
`;

await fs.writeFile(swPath, swContent.trimStart(), 'utf8');
console.log(`✅ Service Worker generated at: ${swPath}`);
console.log(`📦 Cache Name: ${CACHE_NAME}`);
