import type { APIRoute } from 'astro';

const getRobotsTxt = (isProd: boolean, sitemapURL: URL) => {
  if (!isProd) {
    // Block everything on dev or staging
    return `
User-agent: *
Disallow: /
# robots.txt for non-production (blocked)
`;
  }

  // Allow everything except /admin and /api in production
  return `
User-agent: *
Disallow: /admin/
Disallow: /api/
# This robots.txt file is generated by NViewsWeb
Sitemap: ${sitemapURL.href}
`;
};

export const GET: APIRoute = ({ site, request }) => {
  const isProd = import.meta.env.PROD;
  const sitemapURL = new URL('sitemap-index.xml', site);
  return new Response(getRobotsTxt(isProd, sitemapURL), {
    headers: {
      'Content-Type': 'text/plain',
    },
  });
};
