import type { APIRoute } from 'astro';

const getRobotsTxt = (isProd: boolean, sitemapURL: URL) => {
  if (!isProd) {
    // Block everything in dev/staging
    return `User-agent: *
Disallow: /
# robots.txt for non-production (blocked)`;
  }

  // Production robots.txt
  return `User-agent: *
Disallow: /admin/
Disallow: /api/
# This robots.txt file is generated by NViewsWeb
Sitemap: ${sitemapURL.href}`;
};

export const GET: APIRoute = ({ site }) => {
  const isProd = import.meta.env.PROD;
  const sitemapURL = new URL('sitemap.xml', site); // ✅ now only one sitemap

  return new Response(getRobotsTxt(isProd, sitemapURL), {
    headers: {
      'Content-Type': 'text/plain',
    },
  });
};
